server:
  port: 10000

#JDBC datasource
spring:
  datasource:
    hikari:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@localhost:1521:XE
      username: test_pm
      password: 1111

deepsearch:
  api:
    url: https://api-v2.deepsearch.com
    key: 91f8c9d676a5412c9eca82932bc39064